#file name depends clusterGroupName in values-global.yaml
#
clusterGroup:
  name: hub
  isHubCluster: true

  projects:       
  - hub  
  
  namespaces:
  - ingress
  - egress

  subscriptions: {}

  applications: {}
