#file name depends clusterGroupName in values-global.yaml
#
clusterGroup:
  name: hub
  isHubCluster: true

  scheduler:
    mastersSchedulable: true

  namespaces:
  - echo
  - curl
  - egressip-ipam-operator:
      operatorGroup: true
      targetNamespaces: null

  subscriptions:
  - name: egressip-ipam-operator
    channel: alpha
    source: community-operators
    sourceNamespace: openshift-marketplace
    csv: egressip-ipam-operator.v1.2.4

  applications:
    echo:
      name: echo
      namespace: echo
      project: default
      path: charts/echo
    curl:
      name: curl
      namespace: curl
      project: default
      path: charts/curl

vars:
  curl:
    namespace: curl
    url: http://echo-echo.apps.ocp4.gmbros.local/say/hello
    sleep: 5
    node: node03.ocp4.gmbros.local
