#file name depends clusterGroupName in values-global.yaml
#
clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
  - echo

  applications:
    echo:
      name: echo
      namespace: ingress
      project: default
      path: charts/echo
