---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: echo
  name: echo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      deploymentconfig: echo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
        deploymentconfig: echo
      name: echo
    spec:
      containers:
      - name: server
        image: quay.io/soukron/nodejs-echo:v2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
