---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: echo
  name: echo
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: echo
    weight: 100
  wildcardPolicy: None
