---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-configmap
  labels:
    app.kubernetes.io/instance: httpd
data:
  "index.html": |-
    <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="utf-8">
            <title>Hello world</title>
        </head>
          <body>
            <h1>
            Hello world!
            </h1>
          </body>
      </html>
